name: tiny_vision
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - _python_abi3_support=1.0
  - aiodns=3.5.0
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.13.2
  - aiosignal=1.4.0
  - alsa-lib=1.2.14
  - anyio=4.10.0
  - aom=3.9.1
  - arrow-cpp=21.0.0
  - asttokens=3.0.1
  - attrs=25.4.0
  - aws-c-auth=0.9.0
  - aws-c-cal=0.9.2
  - aws-c-common=0.12.4
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.6
  - aws-c-http=0.10.4
  - aws-c-io=0.21.4
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.8.7
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.34.0
  - aws-sdk-cpp=1.11.638
  - blas=1.0
  - bottleneck=1.4.2
  - brotlicffi=1.2.0.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.12.2
  - cairo=1.16.0
  - certifi=2025.11.12
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - click=8.2.1
  - comm=0.2.3
  - contourpy=1.3.3
  - cpython=3.12.12
  - cycler=0.12.1
  - datasets=4.4.2
  - dav1d=1.2.1
  - dbus=1.16.2
  - debugpy=1.8.19
  - decorator=5.2.1
  - dill=0.4.0
  - double-conversion=3.3.1
  - executing=2.2.1
  - expat=2.7.3
  - filelock=3.20.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - fonttools=4.61.0
  - freetype=2.14.1
  - frozenlist=1.8.0
  - fsspec=2025.10.0
  - gettext=0.21.0
  - gflags=2.2.2
  - giflib=5.2.2
  - glog=0.5.0
  - gmp=6.3.0
  - gmpy2=2.2.2
  - graphite2=1.3.14
  - h11=0.16.0
  - harfbuzz=10.2.0
  - hf-xet=1.1.8
  - httpcore=1.0.9
  - httpx=0.28.1
  - huggingface_hub=0.34.4
  - icu=73.2
  - idna=3.11
  - importlib-metadata=8.7.0
  - intel-openmp=2025.0.0
  - ipykernel=7.1.0
  - ipython=9.8.0
  - ipython_pygments_lexers=1.1.1
  - jansson=2.14
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.2
  - jupyter_client=8.7.0
  - jupyter_core=5.9.1
  - keyutils=1.6.3
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libabseil=20250814.1
  - libavif16=1.3.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libclang-cpp18.1=18.1.8
  - libclang13=20.1.8
  - libcups=2.3.3
  - libcurl=8.17.0
  - libde265=1.0.15
  - libdeflate=1.22
  - libdrm=2.4.124
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.3
  - libffi=3.4.4
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libgl=1.7.0
  - libglib=2.80.2
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.2.0
  - libgrpc=1.74.1
  - libheif=1.19.7
  - libhwloc=2.12.1
  - libiconv=1.18
  - libidn2=2.3.8
  - libjpeg-turbo=3.1.2
  - libllvm18=18.1.8
  - libllvm20=20.1.8
  - libnghttp2=1.67.1
  - libnsl=2.0.0
  - libopengl=1.7.0
  - libopenjpeg=2.5.4
  - libpciaccess=0.18
  - libpng=1.6.50
  - libpq=16.11
  - libprotobuf=6.33.0
  - libre2-11=2025.11.05
  - libsodium=1.0.20
  - libsqlite=3.51.1
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libthrift=0.22.0
  - libtiff=4.7.0
  - libtorch=2.7.0
  - libunistring=1.3
  - libuuid=1.41.5
  - libuv=1.48.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxkbcommon=1.9.1
  - libxml2=2.13.9
  - libxslt=1.1.43
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib=3.10.8
  - matplotlib-base=3.10.8
  - matplotlib-inline=0.2.1
  - mkl=2025.0.0
  - mkl-service=2.5.2
  - mkl_fft=2.1.1
  - mkl_random=1.3.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multidict=6.7.0
  - multiprocess=0.70.18
  - mysql-common=8.3.0
  - mysql-libs=8.3.0
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.6.1
  - nltk=3.9.2
  - numexpr=2.14.1
  - numpy=2.3.5
  - numpy-base=2.3.5
  - openjpeg=2.5.4
  - openssl=3.6.0
  - opentelemetry-api=1.38.0
  - orc=2.2.0
  - packaging=25.0
  - pandas=2.3.3
  - parso=0.8.5
  - patsy=1.0.1
  - pcre2=10.43
  - pexpect=4.9.0
  - pillow=11.3.0
  - pip=25.3
  - pixman=0.46.4
  - platformdirs=4.5.1
  - prompt-toolkit=3.0.52
  - propcache=0.4.1
  - psutil=7.1.3
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pyarrow=21.0.0
  - pycares=4.10.0
  - pycparser=2.23
  - pygments=2.19.2
  - pyparsing=3.2.5
  - pyside6=6.7.2
  - pysocks=1.7.1
  - python=3.12.12
  - python-dateutil=2.9.0.post0
  - python-gil=3.12.12
  - python-tzdata=2025.2
  - python-xxhash=3.5.0
  - python_abi=3.12
  - pytz=2025.2
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - qhull=2020.2
  - qt6-main=6.7.2
  - rav1e=0.7.1
  - re2=2025.11.05
  - readline=8.3
  - regex=2025.11.3
  - requests=2.32.5
  - s2n=1.5.14
  - scikit-learn=1.8.0
  - scipy=1.16.3
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=80.9.0
  - six=1.17.0
  - sleef=3.5.1
  - snappy=1.2.1
  - sniffio=1.3.1
  - sqlite=3.51.0
  - stack_data=0.6.3
  - statsmodels=0.14.6
  - svt-av1=3.1.2
  - sympy=1.14.0
  - tbb=2022.3.0
  - tbb-devel=2022.3.0
  - threadpoolctl=3.5.0
  - tk=8.6.15
  - torchvision-extra-decoders=0.0.2
  - tornado=6.5.4
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - urllib3=2.6.1
  - utf8proc=2.6.1
  - uvloop=0.22.1
  - wayland=1.24.0
  - wcwidth=0.2.14
  - wheel=0.45.1
  - x265=3.5
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.44
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxrender=0.9.12
  - xorg-xorgproto=2024.1
  - xxhash=0.8.0
  - xz=5.6.4
  - yaml=0.2.5
  - yarl=1.22.0
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - cuda-bindings==12.9.4
      - cuda-pathfinder==1.2.2
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.28.9
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.4.5
      - nvidia-nvtx-cu12==12.8.90
      - torch==2.11.0.dev20251221+cu128
      - torchaudio==2.10.0.dev20251221+cu128
      - torchvision==0.25.0.dev20251221+cu128
      - triton==3.6.0+git6213a0e8
prefix: /home/punny/anaconda3/envs/tiny_vision
